Exam-Third-main/ExamProjectThird/Models/IntroSlider.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ExamProjectThird.Models
{
    public class IntroSlider
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

Exam-Third-main/ExamProjectThird/Areas/Admin/Controllers/IntroSliderController.cs
using ExamProjectThird.DAL;
using ExamProjectThird.Models;
using ExamProjectThird.Utilities;
using ExamProjectThird.Utilities.FIle;
using ExamProjectThird.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamProjectThird.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class IntroSliderController : Controller
    {
        private IWebHostEnvironment _env;
        private AppDbContext _context;
        public string _errorMessage { get; set; }

       

        public IntroSliderController(IWebHostEnvironment env, AppDbContext context)
        {
            _env = env;
            _context = context;
        }
        // GET: IntroSliderController
        public async Task<IActionResult> Index()
        {
            var IntroSliders = await _context.IntroSliders.ToListAsync();
            return View(IntroSliders);
        }

        // GET: IntroSliderController/Details/5
        public IActionResult Details(int id)
        {

            return View();
        }

        // GET: IntroSliderController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: IntroSliderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MultipleSliderVM multipleSlider)
        {
            try
            {
                if (ModelState["Photos"].ValidationState == ModelValidationState.Invalid) return View();
                if (!CheckImageValid(multipleSlider.Photos))
                {
                    ModelState.AddModelError("Photos", _errorMessage);
                    return View();
                }
                foreach (var photo in multipleSlider.Photos)
                {
                    string fileName = await photo.SaveFileAysnc(_env.WebRootPath, "img");
                    IntroSlider slider = new IntroSlider
                    {
                        ImageUrl = fileName,
                        Description = multipleSlider.Description,
                        Title = multipleSlider.Title

                    };
                    await _context.IntroSliders.AddAsync(slider);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
             
        }

        public bool CheckImageValid(List<IFormFile> photos)
        {
            foreach (var photo in photos)
            {
                if (photos.Count > 5)
                {
                    _errorMessage = $"You can choose a maximum of 5 photo ";
                    return false;
                }

                if (!photo.CheckFileType("image/"))
                {
                    _errorMessage = $"{photo.FileName} must be image type";
                    return false;
                }
                if (!photo.CheckFileSize(3096))
                {
                    _errorMessage = $"{photo.FileName} size must be lest then 3096 kb";
                    return false;
                }

            }
            return true;
        }
        // GET: IntroSliderController/Update/5
        public ActionResult Update(int id)
        {
            return View();
        }

        // POST: IntroSliderController/Update/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, IntroSlider introSlider)
        {
            try
            {
                if (id != introSlider.Id) return BadRequest();
                if (ModelState["Photo"].ValidationState == ModelValidationState.Invalid) return View();

                IntroSlider dbIntroSlider = await _context.IntroSliders.FindAsync(id);
                if (dbIntroSlider == null) return NotFound();

                if (!introSlider.Photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError($"Photo", "File must be image type");
                    return View(dbIntroSlider);
                }
                if (!introSlider.Photo.CheckFileSize(4096))
                {
                    ModelState.AddModelError($"Photo", "File size must be lest than 4 kb");
                    return View(dbIntroSlider);
                }
                Helper.RemoveFile(_env.WebRootPath, "img", dbIntroSlider.ImageUrl);
                string newFileName = await introSlider.Photo.SaveFileAysnc(_env.WebRootPath, "img");
                dbIntroSlider.ImageUrl = newFileName;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: IntroSliderController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            IntroSlider introSlider = await _context.IntroSliders.FindAsync(id);
            if (introSlider == null) return NotFound();
            Helper.RemoveFile(_env.WebRootPath, "img", introSlider.ImageUrl);
            _context.IntroSliders.Remove(introSlider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));



        }

        // POST: IntroSliderController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id)
        //{
        //    try
        //    {

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Exam-Third-main/ExamProjectThird/Areas/Admin/Controllers/WhyChooseController.cs
using ExamProjectThird.DAL;
using ExamProjectThird.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamProjectThird.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WhyChooseController : Controller
    {
        private AppDbContext _context;

        public WhyChooseController(AppDbContext context)
        {
            _context = context;
        }
        // GET: WhyChooseController
        public async Task<ActionResult> Index()
        {
            var WhyChoose = await _context.WhyChoose.Where(w => w.IsDeleted == false).ToListAsync();
            return  View(WhyChoose);
        }

        // GET: WhyChooseController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: WhyChooseController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: WhyChooseController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WhyChoose  whyChoose)
        {
            try
            {
                if (!ModelState.IsValid) return View();             
                bool IsExist = _context.WhyChoose.Any(w => w.Title.Trim().ToLower() == whyChoose.Title.Trim().ToLower());
                if (IsExist)
                {
                    ModelState.AddModelError("Title", "This Name already exist");
                    return View();
                }
                await _context.AddAsync(whyChoose);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));

            }
            catch
            {
                return View();
            }
        }

        // GET: WhyChooseController/Udate/5
        public IActionResult Update(int id)
        {
            WhyChoose whyChoose = _context.WhyChoose.Find(id);
            if (whyChoose == null) return NotFound();
            return View(whyChoose);
        }

        // POST: WhyChooseController/Udate/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, WhyChoose whyChoose)
        {
            try
            {
                if (!ModelState.IsValid) return View();
                if (id != whyChoose.Id) return BadRequest();
                WhyChoose dbWhyChoose = await _context.WhyChoose.Where(w => w.IsDeleted == false && w.Id == id).FirstOrDefaultAsync();
                if (dbWhyChoose.Title.ToLower().Trim() == whyChoose.Title.ToLower().Trim() && dbWhyChoose.Description.ToLower().Trim() == whyChoose.Description.ToLower().Trim())
                {
                    return RedirectToAction(nameof(Index));
                }
                bool IsExist = _context.WhyChoose
                              .Any(c => c.Title.ToLower().Trim() == whyChoose.Title.ToLower().Trim());
                if (IsExist)
                {
                    ModelState.AddModelError("Name", "This Title already exist");
                    return View(dbWhyChoose);
                }
                dbWhyChoose.Title = whyChoose.Title;
                dbWhyChoose.Description = whyChoose.Description;
                await _context.SaveChangesAsync();
          
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WhyChooseController/Delete/5
        //public async Task<IActionResult> Delete(int id)
        //{
           
        //}

        // POST: WhyChooseController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                WhyChoose whyChoose = await _context.WhyChoose.Where(w => w.IsDeleted == false && w.Id == id).FirstOrDefaultAsync();
                if (whyChoose == null) return NotFound();
                whyChoose.IsDeleted = true;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Exam-Third-main/ExamProjectThird/Areas/Admin/Views/IntroSlider/Create.cshtml
@model MultipleSliderVM
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <title>
        Material Dashboard 2 by Creative Tim
    </title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <!-- Nucleo Icons -->
    <link href="../assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="../assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <!-- CSS Files -->
    <link id="pagestyle" href="../assets/css/material-dashboard.css?v=3.0.0" rel="stylesheet" />
</head>

<body class="bg-gray-200">
    <div class="container position-sticky z-index-sticky top-0">
        <div class="row">
            <div class="col-12">
                <!-- Navbar -->
                <nav class="navbar navbar-expand-lg blur border-radius-xl top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
                    <div class="container-fluid ps-2 pe-0">
                        <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3 " href="../pages/dashboard.html">
                            Material Dashboard 2
                        </a>
                        <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon mt-2">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </span>
                        </button>
                        <div class="collapse navbar-collapse" id="navigation">
                            <ul class="navbar-nav mx-auto">
                                <li class="nav-item">
                                    <a class="nav-link d-flex align-items-center me-2 active" aria-current="page" href="../pages/dashboard.html">
                                        <i class="fa fa-chart-pie opacity-6 text-dark me-1"></i>
                                        Dashboard
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link me-2" href="../pages/profile.html">
                                        <i class="fa fa-user opacity-6 text-dark me-1"></i>
                                        Profile
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link me-2" href="../pages/sign-up.html">
                                        <i class="fas fa-user-circle opacity-6 text-dark me-1"></i>
                                        Sign Up
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link me-2" href="../pages/sign-in.html">
                                        <i class="fas fa-key opacity-6 text-dark me-1"></i>
                                        Sign In
                                    </a>
                                </li>
                            </ul>
                            <ul class="navbar-nav d-lg-block d-none">
                                <li class="nav-item">
                                    <a href="https://www.creative-tim.com/product/material-dashboard" class="btn btn-sm mb-0 me-1 bg-gradient-dark">Free download</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- End Navbar -->
            </div>
        </div>
    </div>
    <main class="main-content  mt-0">
        <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
            <span class="mask bg-gradient-dark opacity-6"></span>
            <div class="container my-auto">
                <div class="row">
                    <div class="col-lg-4 col-md-8 col-12 mx-auto">
                        <div class="card z-index-0 fadeIn3 fadeInBottom">
                            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                                <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                                    <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Create New Card</h4>

                                </div>
                            </div>
                            <div class="card-body">
                                <form role="form" class="text-start" method="post" enctype="multipart/form-data">
                                    <div class="input-group input-group-outline my-3">
                                       
                                        <input asp-for="Photos" class="form-control">
                                    </div>
                                    <div class="input-group input-group-outline my-3">
                                        <label asp-for="Title" class="form-label"></label>
                                        <input asp-for="Title" class="form-control">
                                    </div>
                                    <div class="input-group input-group-outline mb-3">
                                        <span class="text-danger" asp-validation-for="Title"></span>
                                    </div>
                                    <label asp-for="Description" class="form-label"></label>
                                    <div class="input-group input-group-outline mb-3">
                                        <textarea class="form-control" asp-for="Description"></textarea>
                                    </div>
                                    <div class="input-group input-group-outline mb-3">
                                        <span class="text-danger" asp-validation-for="Description"></span>
                                    </div>

                                    <div class="text-center">
                                        <button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Create</button>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="footer position-absolute bottom-2 py-2 w-100">
                <div class="container">
                    <div class="row align-items-center justify-content-lg-between">
                        <div class="col-12 col-md-6 my-auto">
                            <div class="copyright text-center text-sm text-white text-lg-start">
                                ©
                                <script>
                  document.write(new Date().getFullYear())
                                </script>,
                                made with <i class="fa fa-heart" aria-hidden="true"></i> by
                                <a href="https://www.creative-tim.com" class="font-weight-bold text-white" target="_blank">Creative Tim</a>
                                for a better web.
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                                <li class="nav-item">
                                    <a href="https://www.creative-tim.com" class="nav-link text-white" target="_blank">Creative Tim</a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://www.creative-tim.com/presentation" class="nav-link text-white" target="_blank">About Us</a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://www.creative-tim.com/blog" class="nav-link text-white" target="_blank">Blog</a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-white" target="_blank">License</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </main>
    <!--   Core JS Files   -->
    <script src="../assets/js/core/popper.min.js"></script>
    <script src="../assets/js/core/bootstrap.min.js"></script>
    <script src="../assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="../assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
    </script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="../assets/js/material-dashboard.min.js?v=3.0.0"></script>
</body>

</html>

Exam-Third-main/ExamProjectThird/Areas/Admin/Views/IntroSlider/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model IEnumerable<IntroSlider>


<h1>Index</h1>

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                        <h6 class="text-white text-capitalize ps-3">Authors table</h6>
                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Image</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Title</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Description</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>

                                    <td>

                                        <div class="card-header p-0 mt-n4 mx-3">
                                            <a class="d-block shadow-xl border-radius-xl">
                                                <img src="@item.ImageUrl" alt="img-blur-shadow" class="img-fluid shadow border-radius-xl">
                                            </a>
                                        </div>
                                    </td>
                                    <td>

                                        <div>
                                            @Html.Raw(item.Title)
                                        </div>


                                    </td>
                                    <td>

                                        <textarea readonly class="text-xs font-weight-bold mb-0 form-control">@Html.Raw(item.Description)</textarea>

                                    </td>
                                    <td>
                                        <form method="post">
                                            <button asp-area="Admin" type="submit" asp-controller="IntroSlider" asp-action="Delete" data-id="@item.Id" data-name="Card" asp-route-id="@item.Id" class="btn btn-book text-danger px-2 m-0 delete-item"> <i class="fas fa-trash"></i></button>
                                            <a class="text-secondary" asp-controller="WhyChoose" asp-action="Update" asp-route-id="@item.Id"><i class="far fa-edit px-2 "></i></a>

                                        </form>


                                    </td>
                                </tr>
                                }


                            </tbody>
                        </table>
                        <a asp-area="Admin" class="btn btn-book" asp-controller="IntroSlider" asp-action="Create"> Create</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>